version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sw_starter_app
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      # Código da aplicação
      - .:/var/www/html

      # Evita problemas de permissão
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - redis
    networks:
      - sw_starter-network
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # Redis para cache, filas e estatísticas
  redis:
    image: redis:7-alpine
    container_name: sw_starter_redis
    ports:
      - "6379:6379"
    networks:
      - sw_starter-network

  # Worker de filas (opcional, mas recomendado)
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sw_starter_queue
    working_dir: /var/www/html
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - app
      - redis
    networks:
      - sw_starter-network

  # Scheduler (cron do Laravel)
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sw_starter_scheduler
    working_dir: /var/www/html
    command: php artisan schedule:work
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - app
      - redis
    networks:
      - sw_starter-network

networks:
  sw_starter-network:
    driver: bridge
